version: '3'
services:

  eureka-serviceregistry:
    build: ./Eureka
    ports:
     - "8761:8761"
    tty: true

  ad:
  
    build: ./ad
    ports:
    - "8081:8081"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      
      




  aut-s:
    build: ./aut-s
    ports:
    - "8082:8082"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
  
  zuul:

    
    

    build: ./Zuul
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry

    tty: true
 
    depends_on:
      - eureka-serviceregistry
      - ad

  docker-mysql:
    restart: always
    container_name: docker-mysql-ad-service
    image: mysql
    environment:
      MYSQL_DATABASE: ad_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

    volumes:

      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "52000:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  
  docker-mysql-aut-s:
    restart: always
    container_name: docker-mysql-aut-service
    image: mysql
    environment:
      MYSQL_DATABASE: aut_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

    volumes:

      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "52001:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  
