version: '3'
services:

  eureka-serviceregistry:
    build: ./Eureka
    ports:
     - "8761:8761"
    tty: true

  ad:
    build: ./ad
    ports:
    - "8081:8081"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  zuul:
    build: ./Zuul
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - ad

  

  
